version: "3"
services:
  simple-transaction:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_started
        restart: true
    ports:
      - "8000:8000"

  db:
    image: postgres:12
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  db-data:
